// DOMManipulation_Checkpoint/angular-todo/src/app/ui/task-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Priority, Task } from '../task/task.model';
import { TaskItemComponent } from './task-item.component';

@Component({
  selector: 'app-task-list',
  standalone: true,
  imports: [TaskItemComponent],
  templateUrl: './task-list.component.html',
})
export class TaskListComponent {
  @Input({ required: true }) tasks!: Task[];
  @Output() update = new EventEmitter<{ id: string; name: string; priority: Priority }>();
  @Output() remove = new EventEmitter<string>();
}

@if (tasks.length === 0) {
  <div class="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500 dark:border-slate-700 dark:text-slate-400">
    No tasks yet — add one above.
  </div>
} @else {
  <ul class="flex flex-col gap-2">
    @for (task of tasks; track task.id) {
      <app-task-item [task]="task" (update)="update.emit($event)" (remove)="remove.emit($event)" />
    }
  </ul>
}

// DOMManipulation_Checkpoint/vue-todo/src/ui/TaskList.vue
<script setup>
import TaskItem from './TaskItem.vue'

defineProps({
  tasks: { type: Array, required: true },
})
defineEmits(['update', 'remove'])
</script>

<template>
  <div
    v-if="tasks.length === 0"
    class="rounded-xl border border-dashed border-slate-300 p-6 text-center text-sm text-slate-500 dark:border-slate-700 dark:text-slate-400"
  >
    No tasks yet — add one above.
  </div>
  <ul v-else class="flex flex-col gap-2">
    <TaskItem
      v-for="task in tasks"
      :key="task.id"
      :task="task"
      @update="(...args) => $emit('update', ...args)"
      @remove="(id) => $emit('remove', id)"
    />
  </ul>
</template>
